# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

sudo: required

cache: packages

env: _R_CHECK_CRAN_INCOMING_=FALSE

r_github_packages:
  - jimhester/covr
  - kuperov/adsample

after_success:
  - Rscript -e 'library(covr);codecov()'
